name: Deploy Sweet Point

on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Melakukan unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Verify
        run: mvn clean verify
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.TOKEN_DOCKER }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          file: unit-test.dockerfile
          context: .
          push: true
          tags: kokolaz/capstone-sweet-point-coverage:latest
  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: run_test
    steps:
      - run: echo "Starting build package"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Build
        run: mvn clean package -Dmaven.test.skip=true
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.TOKEN_DOCKER }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kokolaz/capstone-sweet-point:latest
  deployment:
    name: Deploy container using SSH
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - run: echo "Starting deploy container"
      - uses: actions/checkout@v3
      - name: Copy environment file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dev.env
          target: /home/${{ secrets.SSH_USERNAME }}
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop capstone-sweet-point capstone-sweet-point-coverage
            docker rmi kokolaz/capstone-sweet-point:latest kokolaz/capstone-sweet-point-coverage:latest
            docker pull kokolaz/capstone-sweet-point:latest
            docker pull kokolaz/capstone-sweet-point-coverage:latest
            docker run -d --rm --name capstone-sweet-point-coverage -p 8000:80 kokolaz/capstone-sweet-point-coverage:latest
            docker run -d --rm --name capstone-sweet-point -p 80:8080 --env-file=dev.env --network network1 kokolaz/capstone-sweet-point:latest